### ISSUE TITLE
Add portal-specific graphs in Overview section

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_browser_client#98]
Which graphs that are being shown in the result overview section should change depending on which portal is selected.

Some preliminary suggestions (from @visead) are:

* Dendro
  * Building types
  * Identified provenance
  * @MattiasSealander more/other?

* Isotopes
  * Chemical elements?
  * Maybe Mats has some ideas? @MGE4 

* Ceramics
  * Temper/margin something maybe...? @MattiasSealander 

* Insects
  * Eco codes (the bugs ones, not the Koch ones)

**Comment by MattiasSealander** [comment]
Off the top of my head:

Dendro

- Building types
- Identified tree species
- If possible, summary of the outermost tree ring date (time line? bar graph? histogram?)
- Summary dated/not dated samples (not sure if they want, need input from dendro people)

Do we need to distinguish between dendro for building and archaeology? Archaeological features can be interesting, but of course mainly to archaeologists?

Ceramics
Difficult due to how results are recorded. Perhaps mainly metadata.

- Dating (relative age)
- Culture (think it was registered in sample group somewhere)
- Vessel type (if vessel)
- Sample type (possibly through the above)

We would need some way of telling the primary temper, which is difficult at the moment, in order to provide a simple graphic summarizing it. At the moment, this is impossible.





    Identified provenance
    @MattiasSealander more/other?

**Comment by MGE4** [comment]
As far as isotopes go i would have to say 

- summary of isotope type in samples
- isotope analysis method
- material sampled (i.e bone, ceramic matrix - internal, ceramic matrix - internal, charred deposit - internal, etc.)
- relative_ages

I will wright a pathway to the different parameters ASAP.

**Comment by MGE4** [comment]
Isotope information in descending priority
Count or percentages can be changed depending on what Phill think is cooler.
Site distribution shold absolutely be kept as is.

1) Isotope types found in samples:

SELECT SUM(designation)
FROM tbl_isotope_types
WHERE tbl_isotope_types.isotope_type_id = tbl_isotope_measurments.isotope_type_id;


2) Isotope methods used:

SELECT SUM(method_name)
FROM tbl_methods
WHERE tbl_methods.method_id = tbl_isotope_measurments.method_id;


3) Materials sampled:

SELECT SUM(location)
FROM tbl_sample_lacations
WHERE tbl_sample_locations.sample_location_type_id = tbl_sample_locations.sample_location_type_id
AND tbl_sample_locations.sample_location_type = 2;


4) Archaeological Time periods:

SELECT SUM(relative_age_name)
FROM tbl_relative_ages
WHERE tbl_relative_ages.relative_age_id = tbl_relative_date.relative_age_id;



I haven't been able to test this but i hope you can see what im trying to do here.

**Comment by johanvonboer** [comment]
@MGE4 I tried implementing some of your suggestions Mats but I got some strange results for 3/4 of them. SQL is not my strong point so I might have made some mistake somewhere in my implementations, but this is what I got:

1. SQL: 
SELECT isotope_types.designation, COUNT(isotope_types.designation)
FROM postgrest_api.isotope_types
INNER JOIN postgrest_api.isotope_measurements ON isotope_types.isotope_type_id = isotope_measurements.isotope_type_id
GROUP BY isotope_types.designation;

RESULT:
![image](https://user-images.githubusercontent.com/34707290/77792128-18034a80-7068-11ea-8e48-87a6578bc952.png)

COMMENT:
It just seems strange that they all have a count of 944, except 2. Will this change in the future to be more diverse?

2. SQL:
SELECT DISTINCT(methods.method_name)
FROM postgrest_api.methods
INNER JOIN postgrest_api.isotope_measurements ON methods.method_id = isotope_measurements.method_id;

RESULT:
![image](https://user-images.githubusercontent.com/34707290/77792309-73cdd380-7068-11ea-88b8-edd0817ebcf2.png)

COMMENT:
Just one result... Seems like it's all under 1 method?

3. SQL:
SELECT *
FROM postgrest_api.sample_locations
WHERE sample_locations.sample_location_type_id = 2;

RESULT:
No screenshot here because the result is simply zero - no rows! :(

The last one works quite well, got a list of about 600+ items with some various counts. But the previous 3 has some strange results in different ways. I can't really create meaningful graphs out of those as it is now - which isn't really a problem, I just thought I would raise the issue so that you are aware of the situation - maybe there's a problem in the data somehow?

**Comment by MGE4** [comment]
Yea, the thing is that we only got a small data set from one lab, so the data that is in SEAD at the moment will be a bit boring in that way, but as soon as we get some new data it will change and look a lot more interesting. 

1) This looks good, this will change in  the future. Im curious what the 2832 samples with 13c/12c ratio, are... im gonna have a look at that.

2) yes its all under one method but there are multiple methods of doing isotope analysis, so this will also change in the future with more labs sending there data. But what i waned it to show was how many samples there are under the different methods, not just showing the methods.

3) What i wanted to show with the third one was what different materials that were sampled in the data we got, this shold show something like: ceramic matrix - internal, ceramic matrix - internal, charred deposit - internal, etc. and the count of how many of each. If that makes any sence.

Note: Moust of the data will not show anything interesting at this moment, but once new data comes in, this will be more exciting.

**Comment by MattiasSealander** [comment]
Uncertain of whether you've already done your own SQL, but in any case here are some that you can use as frameworks for extracting relevant dendro/ceramics info. Simply add line which updates based on selected site_id.

DENDRO

- Building types
SQL below fetches the represented categories of buildings in sample_group_description_types. Need to talk with dendro people regarding what information is most important. description_type_id 62 used now have few and vague building types, id 61 could be used and has clearer identification of building purpose, but also features concats related to individual investigations.

SELECT
DISTINCT sgd.group_description,
COUNT(ps.physical_sample_id) AS "No. of samples"
FROM tbl_sites s 
join tbl_sample_groups sg on s.site_id = sg.site_id
join tbl_sample_group_descriptions sgd on sg.sample_group_id = sgd.sample_group_id
join tbl_sample_group_description_types sgdt on sgd.sample_group_description_type_id = sgdt.sample_group_description_type_id
join tbl_physical_samples ps on ps.sample_group_id = sg.sample_group_id
WHERE 
sgdt.sample_group_description_type_id = 62
GROUP BY 
sgd.group_description

-Tree species
The SQL below should retrieve the genus for the samples with a positive identification of tree species. The species is genus level retrieved from the taxa tree, since there is a variation in how the lab recorded it in tbl_dendro. The count is done on physical_samples, which corresponds to the dendro lab CATRAS sample numbers. 

SELECT
ttg.genus_name,
COUNT(ps.physical_sample_id)

FROM tbl_sites s 
join tbl_sample_groups sg on s.site_id = sg.site_id
join tbl_physical_samples ps on sg.sample_group_id = ps.sample_group_id
join tbl_analysis_entities ae on ps.physical_sample_id = ae.physical_sample_id
join tbl_dendro d on ae.analysis_entity_id = d.analysis_entity_id
join tbl_dendro_lookup dl on dl.dendro_lookup_id = d.dendro_lookup_id
join tbl_abundances a on a.analysis_entity_id = ae.analysis_entity_id
join tbl_taxa_tree_master ttm on ttm.taxon_id = a.taxon_id
join tbl_taxa_tree_genera ttg on ttg.genus_id = ttm.genus_id

WHERE 

dl.dendro_lookup_id = 121

GROUP BY
ttg.genus_name

WILL EDIT AS I MAKE MORE SQL

**Comment by johanvonboer** [comment]
@MattiasSealander Great stuff Mattias - thanks! Haven't had time to start looking at it yet but hoping tomorrow.

**Comment by johanvonboer** [comment]
Btw - If you have access to the sead_production db (not sure if you do?) on seadserv then if you create the views in the postgrest_api-schema there then that would be super awesome for me because any views in there automatically becomes accessible via URLs like: https://browser.sead.se:3000/qse_site_dataset_biblio?site_id=eq.1980 

So then I can just call on them directly in the code. But if you don't have access then no worries, giving me SQL here is super helpful as well

**Comment by MattiasSealander** [comment]
I've added a couple of views, please try and see if they work as intended.

**Comment by johanvonboer** [comment]
@MattiasSealander Sounds great - but which ones? :)

**Comment by MattiasSealander** [comment]
In the above edited comment, the names in the bullet list are the names they have in the DB.

**Comment by johanvonboer** [comment]
I have done some work on this now and new charts for ceramics and dendro are up at the new site:
https://browser.sead.se/

At their respective portals:
https://browser.sead.se/ceramic
https://browser.sead.se/dendro

I modified your views a little @MattiasSealander to include site_id's as well, this makes them a lot less efficient to fetch, but it enabled the graphs to be dynamic and change according to the current filter selection, which I think is cool :) (and maybe useful?)

I couldn't figure out the view for dendro_dated_samples though, so I left that out for now. Perhaps you can make a view for dummies - or fix it so that it works the same way as the others?

I might build a proper server for delivering the data for these charts in the future instead of just relying on PostgREST since that would speed up the loading a lot, but for now it's more efficient in terms of coding time to just do it like this. Even if I do these views would still be used though, so there's no time lost.

Will get around to implementing the isotopes ones as well.

**Comment by johanvonboer** [comment]
Btw, I added a "qse_" prefix to the names, just so I know which views in that schema are made by us and which are just the default 1:1 mappings to the tables created by PostgREST. So e.g. dendro_tree_species is now called qse_dendro_tree_species, just so you know where to find them.

**Comment by MattiasSealander** [comment]
Need to discuss how to handle dendro archaeological data. When selecting an archaeological site in the dendro data, building specific graphics will fail. Further discussion in new issue?

**Comment by johanvonboer** [comment]
> Need to discuss how to handle dendro archaeological data. When selecting an archaeological site in the dendro data, building specific graphics will fail. Further discussion in new issue?

Sure! Feel free to create a new issue for it.
